name: nottacafe
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  flutter_switch: ^0.3.2
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.7
  image_picker: ^0.8.6+1
  firebase_storage: ^11.0.10
  cross_file: ^0.3.3+4
  fluttertoast: ^8.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  assets:
    # Add assets from the images directory to the application.
    - assets/images/bg.png
    - assets/images/bg2.png
    - assets/images/bgdark.png
    - assets/images/nottingham_background.jpg
    - assets/images/error_image.png
